
export const BakingData =() => [
{ id: 1,
    name: 'Pre-feed (starter refresh)',
    purpose: 'Feed the starter so that they are powerful enough to make good bread',
    hours: 8,
    minutes: 0, 
    subtask: '',
}, 
{ id: 2,
  name: '"Levain" building',
  purpose: 'Give 1:1:1 feed to build sourdough sterter that goes into the dough mix',
  hours: 4,
  minutes: 0, 
  subtask: '',
}, 
{ id: 3,
  name: 'Autolyse',
  purpose: 'Incorporate flour and water. Helps gluten network to start building',
  hours: 0,
  minutes: 30, 
  subtask: '',
}, {
 id: 4,
 name: 'Mixing',
 purpose: 'Incorporate all the rest of the ingredients. Ensure to leave no lamps',
 hours: 0,
 minutes: 20, 
 subtask: '',
}, {
 id: 5,
 name: 'Bulk Fermentation',
 purpose: 'Help gluten network to build. Give time for yeast to grow',
 hours: 5,
 minutes: 0, 
 subtask: '',
}, {
 id: 6,
 name: 'Preshaping',
 purpose: 'Tightening the dough to set them up for final shaping. ',
 hours: 0,
 minutes: 10, 
 subtask: '',
}, {
 id: 7,
 name: 'Baking-1',
 purpose: 'Give high heat to rise the bread quickly',
 hours: 0,
 minutes: 20, 
 subtask: '',
}, { 
 id: 8,
 name: 'Baking-2',
 purpose: 'Bake up to beautifully brown your loaf at lower temperarure',
 hours: 0,
 minutes: 20, 
 subtask: '',
}
]

