name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # The build job
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.17.6
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm      
      - run: npm ci
      - run: npm test
      - run: npm run build
      
  
